pipeline {
    agent any

    tools {
        jdk 'Java21'
        maven 'Maven'
    }
stages {
	stage('Checkout') {
		steps {
			git branch: 'main',
			url:' https://github.com/vemula2448/second_Testing.git'
							}
						}
	stage('Build') {
		steps {
			dir('praveen/vemula-new') {
            bat 'mvn clean package'
        }
    }
}
	stage('Archive WAR') {
		steps {
			archiveArtifacts artifacts: 'praveen/vemula-new/target/*.war'
			}
		}
stage('Copy WAR to Vagrant') {
    steps {
        bat 'scp -P 2222 -i "C:\\Users\\Vemula\\vagrant-vm\\centos\\.vagrant\\machines\\default\\virtualbox\\private_key" "C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\Second-Build\\praveen\\vemula-new\\target\\secondarDockerApp.war" vagrant@127.0.0.1:/home/vagrant/'
    }
}
	}
}