pipeline {
    agent any

    tools {
        jdk 'Java21'
        maven 'Maven'
    }
stages {
	stage('Checkout') {
		steps {
			git branch: 'main',
			url:' https://github.com/vemula2448/second_Testing.git'
							}
						}
	stage('Build') {
		steps {
			dir('praveen/vemula-new') {
            bat 'mvn clean package'
        }
    }
}
	stage('Archive WAR') {
		steps {
			archiveArtifacts artifacts: 'praveen/vemula-new/target/*.war'
			}
		}
stage('Check Docker Version') {
    steps {
        bat 'ssh -p 2222 -i "C:\\Users\\Vemula\\vagrant-vm\\centos\\.vagrant\\machines\\default\\virtualbox\\private_key" vagrant@127.0.0.1 "sudo docker --version"'
    }
}

stage('Build Docker Image') {
    steps {
        bat '''
        ssh -p 2222 -i "C:\\Users\\Vemula\\vagrant-vm\\centos\\.vagrant\\machines\\default\\virtualbox\\private_key" vagrant@127.0.0.1 "cd /home/vagrant/secodary_App && sudo docker build -t seconddockerapp:v1 ."
        '''
    }
}

stage('Deploy Container') {
    steps {
        bat '''
        ssh -p 2222 -i "C:\\Users\\Vemula\\vagrant-vm\\centos\\.vagrant\\machines\\default\\virtualbox\\private_key" vagrant@127.0.0.1 "sudo docker rm -f seconddockerapp 2>/dev/null || true && sudo docker run -d --name seconddockerapp -p 8080:8080 seconddockerapp:v1"
        '''
    }
}

stage('Verify Deployment') {
    steps {
        bat '''
        ssh -p 2222 -i "C:\\Users\\Vemula\\vagrant-vm\\centos\\.vagrant\\machines\\default\\virtualbox\\private_key" vagrant@127.0.0.1 "sudo docker ps"
        '''
    }
}
	post {
        always {
            echo 'Pipeline execution completed.'
        }

        success {
            echo 'Application deployed successfully.'
        }

        failure {
            echo 'Pipeline failed. Please check the console output.'
        }
    }
}
